<?php

namespace Database\Seeders;

use App\Models\Products;
use App\Models\ProductImage;
use App\Models\Brands;
use App\Models\Category;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // جلب الـ IDs
        $apple = Brands::where('slug', 'apple')->first()->id;
        $samsung = Brands::where('slug', 'samsung')->first()->id;
        $xiaomi = Brands::where('slug', 'xiaomi')->first()->id;
        $huawei = Brands::where('slug', 'huawei')->first()->id;
        $oppo = Brands::where('slug', 'oppo')->first()->id;
        $lenovo = Brands::where('slug', 'lenovo')->first()->id;
        $hp = Brands::where('slug', 'hp')->first()->id;
        $asus = Brands::where('slug', 'asus')->first()->id;

        $phone = Category::where('slug', 'phone')->first()->id;
        $laptops = Category::where('slug', 'laptops')->first()->id;
        $tablets = Category::where('slug', 'tablets')->first()->id;
        $headphones = Category::where('slug', 'headphones')->first()->id;
        $smartWatches = Category::where('slug', 'smart-watches')->first()->id;
        $gaming = Category::where('slug', 'gaming')->first()->id;

        $products = [
            // ========== Apple iPhones ==========
            [
                'title' => 'iPhone 15 Pro Max - 256GB - Natural Titanium',
                'slug' => 'iphone-15-pro-max-256gb-natural-titanium',
                'summary' => 'أحدث iPhone مع شاشة Super Retina XDR',
                'description' => '<p>iPhone 15 Pro Max مع شاشة 6.7 بوصة OLED، معالج A17 Pro، كاميرا 48MP رئيسية + 12MP ultra-wide + 12MP telephoto، وتقنية USB-C.</p>',
                'cat_id' => $phone,
                'child_cat_id' => Category::where('slug', 'iphone')->first()->id,
                'price' => 72999,
                'discount' => 5,
                'brand_id' => $apple,
                'status' => 'active',
                'stock' => 50,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => '256GB',
                'image' => 'products/iphone-15-pro-max.jpg',
            ],
            [
                'title' => 'iPhone 15 Pro - 128GB - Blue Titanium',
                'slug' => 'iphone-15-pro-128gb-blue-titanium',
                'summary' => 'iPhone 15 Pro مع Dynamic Island',
                'description' => '<p>شاشة 6.1 بوصة OLED، معالج A17 Pro، كاميرا 48MP، تصميم تيتانيوم.</p>',
                'cat_id' => $phone,
                'child_cat_id' => Category::where('slug', 'iphone')->first()->id,
                'price' => 62999,
                'discount' => 3,
                'brand_id' => $apple,
                'status' => 'active',
                'stock' => 40,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => '128GB',
                'image' => 'products/iphone-15-pro.jpg',
            ],
            [
                'title' => 'iPhone 15 - 256GB - Pink',
                'slug' => 'iphone-15-256gb-pink',
                'summary' => 'iPhone 15 مع Dynamic Island',
                'description' => '<p>شاشة 6.1 بوصة، معالج A16 Bionic، كاميرا 48MP، منفذ USB-C.</p>',
                'cat_id' => $phone,
                'child_cat_id' => Category::where('slug', 'iphone')->first()->id,
                'price' => 49999,
                'discount' => 0,
                'brand_id' => $apple,
                'status' => 'active',
                'stock' => 60,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => '256GB',
                'image' => 'products/iphone-15.jpg',
            ],
            [
                'title' => 'iPhone 14 Pro Max - 256GB - Space Black',
                'slug' => 'iphone-14-pro-max-256gb-space-black',
                'summary' => 'iPhone 14 Pro Max مع كاميرا 48MP',
                'description' => '<p>شاشة 6.7 بوصة Always-On، كاميرا احترافية، معالج A16 Bionic.</p>',
                'cat_id' => $phone,
                'child_cat_id' => Category::where('slug', 'iphone')->first()->id,
                'price' => 64999,
                'discount' => 10,
                'brand_id' => $apple,
                'status' => 'active',
                'stock' => 25,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => '256GB',
                'image' => 'products/iphone-14-pro-max.jpg',
            ],

            // ========== Samsung ==========
            [
                'title' => 'Samsung Galaxy S24 Ultra - 512GB - Titanium Gray',
                'slug' => 'samsung-galaxy-s24-ultra-512gb-titanium-gray',
                'summary' => 'أقوى جهاز Samsung مع AI',
                'description' => '<p>شاشة 6.8 بوصة Dynamic AMOLED 2X، معالج Snapdragon 8 Gen 3، كاميرا 200MP، قلم S Pen مدمج.</p>',
                'cat_id' => $phone,
                'child_cat_id' => Category::where('slug', 'samsung-galaxy')->first()->id,
                'price' => 54999,
                'discount' => 8,
                'brand_id' => $samsung,
                'status' => 'active',
                'stock' => 35,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => '512GB',
                'image' => 'products/samsung-s24-ultra.jpg',
            ],
            [
                'title' => 'Samsung Galaxy S24+ - 256GB - Cobalt Violet',
                'slug' => 'samsung-galaxy-s24-plus-256gb-cobalt-violet',
                'summary' => 'Galaxy S24+ مع Galaxy AI',
                'description' => '<p>شاشة 6.7 بوصة، معالج Snapdragon 8 Gen 3، كاميرا 50MP، بطارية 4900mAh.</p>',
                'cat_id' => $phone,
                'child_cat_id' => Category::where('slug', 'samsung-galaxy')->first()->id,
                'price' => 42999,
                'discount' => 5,
                'brand_id' => $samsung,
                'status' => 'active',
                'stock' => 45,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => '256GB',
                'image' => 'products/samsung-s24-plus.jpg',
            ],
            [
                'title' => 'Samsung Galaxy Z Fold 5 - 512GB - Phantom Black',
                'slug' => 'samsung-galaxy-z-fold-5-512gb-phantom-black',
                'summary' => 'الجيل الخامس من الهواتف القابلة للطي',
                'description' => '<p>شاشة 7.6 بوصة قابلة للطي، معالج Snapdragon 8 Gen 2، 12GB RAM.</p>',
                'cat_id' => $phone,
                'child_cat_id' => Category::where('slug', 'samsung-galaxy')->first()->id,
                'price' => 69999,
                'discount' => 12,
                'brand_id' => $samsung,
                'status' => 'active',
                'stock' => 15,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => '512GB',
                'image' => 'products/samsung-z-fold-5.jpg',
            ],

            // ========== Xiaomi ==========
            [
                'title' => 'Xiaomi 14 Ultra - 512GB - White',
                'slug' => 'xiaomi-14-ultra-512gb-white',
                'summary' => 'تصوير احترافي مع Leica',
                'description' => '<p>شاشة 6.73 بوصة LTPO AMOLED، كاميرا 50MP Leica، معالج Snapdragon 8 Gen 3.</p>',
                'cat_id' => $phone,
                'child_cat_id' => null,
                'price' => 39999,
                'discount' => 7,
                'brand_id' => $xiaomi,
                'status' => 'active',
                'stock' => 30,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => '512GB',
                'image' => 'products/xiaomi-14-ultra.jpg',
            ],
            [
                'title' => 'Xiaomi Redmi Note 13 Pro+ - 256GB - Midnight Black',
                'slug' => 'xiaomi-redmi-note-13-pro-plus-256gb-midnight-black',
                'summary' => 'أداء ممتاز بسعر منافس',
                'description' => '<p>شاشة 6.67 بوصة 120Hz، كاميرا 200MP، شحن 120W.</p>',
                'cat_id' => $phone,
                'child_cat_id' => null,
                'price' => 12999,
                'discount' => 0,
                'brand_id' => $xiaomi,
                'status' => 'active',
                'stock' => 100,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => '256GB',
                'image' => 'products/redmi-note-13-pro-plus.jpg',
            ],

            // ========== Laptops ==========
            [
                'title' => 'MacBook Pro 14" M3 - 512GB - Space Gray',
                'slug' => 'macbook-pro-14-m3-512gb-space-gray',
                'summary' => 'لابتوب Apple احترافي',
                'description' => '<p>معالج Apple M3، شاشة Liquid Retina XDR 14.2 بوصة، 18GB RAM، بطارية حتى 22 ساعة.</p>',
                'cat_id' => $laptops,
                'child_cat_id' => Category::where('slug', 'work-laptops')->first()->id,
                'price' => 89999,
                'discount' => 0,
                'brand_id' => $apple,
                'status' => 'active',
                'stock' => 20,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => '512GB',
                'image' => 'products/macbook-pro-14.jpg',
            ],
            [
                'title' => 'MacBook Air 15" M2 - 256GB - Midnight',
                'slug' => 'macbook-air-15-m2-256gb-midnight',
                'summary' => 'أخف وأنحف MacBook',
                'description' => '<p>معالج M2، شاشة 15.3 بوصة Liquid Retina، 8GB RAM، وزن 1.51kg.</p>',
                'cat_id' => $laptops,
                'child_cat_id' => Category::where('slug', 'work-laptops')->first()->id,
                'price' => 54999,
                'discount' => 5,
                'brand_id' => $apple,
                'status' => 'active',
                'stock' => 30,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => '256GB',
                'image' => 'products/macbook-air-15.jpg',
            ],
            [
                'title' => 'Lenovo Legion Pro 7i - 1TB - Onyx Grey',
                'slug' => 'lenovo-legion-pro-7i-1tb-onyx-grey',
                'summary' => 'لابتوب ألعاب قوي',
                'description' => '<p>معالج Intel Core i9-13900HX، RTX 4080، شاشة 16 بوصة 240Hz، 32GB RAM.</p>',
                'cat_id' => $laptops,
                'child_cat_id' => Category::where('slug', 'gaming-laptops')->first()->id,
                'price' => 79999,
                'discount' => 15,
                'brand_id' => $lenovo,
                'status' => 'active',
                'stock' => 10,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => '1TB',
                'image' => 'products/lenovo-legion-pro-7i.jpg',
            ],
            [
                'title' => 'HP Omen 16 - 512GB - Shadow Black',
                'slug' => 'hp-omen-16-512gb-shadow-black',
                'summary' => 'لابتوب ألعاب من HP',
                'description' => '<p>معالج AMD Ryzen 7 7840HS، RTX 4060، شاشة 16.1 بوصة 165Hz، 16GB RAM.</p>',
                'cat_id' => $laptops,
                'child_cat_id' => Category::where('slug', 'gaming-laptops')->first()->id,
                'price' => 45999,
                'discount' => 10,
                'brand_id' => $hp,
                'status' => 'active',
                'stock' => 18,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => '512GB',
                'image' => 'products/hp-omen-16.jpg',
            ],
            [
                'title' => 'ASUS ROG Strix Scar 16 - 1TB - Eclipse Gray',
                'slug' => 'asus-rog-strix-scar-16-1tb-eclipse-gray',
                'summary' => 'ملك لابتوبات الألعاب',
                'description' => '<p>معالج Intel Core i9-14900HX، RTX 4090، شاشة 16 بوصة Mini LED 240Hz، 64GB RAM.</p>',
                'cat_id' => $laptops,
                'child_cat_id' => Category::where('slug', 'gaming-laptops')->first()->id,
                'price' => 129999,
                'discount' => 8,
                'brand_id' => $asus,
                'status' => 'active',
                'stock' => 5,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => '1TB',
                'image' => 'products/asus-rog-strix-scar-16.jpg',
            ],

            // ========== Tablets ==========
            [
                'title' => 'iPad Pro 12.9" M2 - 256GB - Space Gray',
                'slug' => 'ipad-pro-12-9-m2-256gb-space-gray',
                'summary' => 'أقوى iPad على الإطلاق',
                'description' => '<p>شاشة 12.9 بوصة Liquid Retina XDR، معالج M2، Face ID، دعم Apple Pencil 2.</p>',
                'cat_id' => $tablets,
                'child_cat_id' => null,
                'price' => 54999,
                'discount' => 0,
                'brand_id' => $apple,
                'status' => 'active',
                'stock' => 25,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => '256GB',
                'image' => 'products/ipad-pro-12-9.jpg',
            ],
            [
                'title' => 'iPad Air 11" M2 - 128GB - Blue',
                'slug' => 'ipad-air-11-m2-128gb-blue',
                'summary' => 'iPad Air الجديد مع M2',
                'description' => '<p>شاشة 11 بوصة Liquid Retina، معالج M2، دعم Apple Pencil Pro.</p>',
                'cat_id' => $tablets,
                'child_cat_id' => null,
                'price' => 29999,
                'discount' => 3,
                'brand_id' => $apple,
                'status' => 'active',
                'stock' => 40,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => '128GB',
                'image' => 'products/ipad-air-11.jpg',
            ],
            [
                'title' => 'Lenovo IdeaTab P12 - 256GB - Storm Grey',
                'slug' => 'lenovo-ideatab-p12-256gb-storm-grey',
                'summary' => 'تابلت Lenovo بشاشة 2.5K',
                'description' => '<p>شاشة 12.7 بوصة 2.5K 90Hz، معالج Dimensity 7050، 8GB RAM، مع قلم وكيبورد.</p>',
                'cat_id' => $tablets,
                'child_cat_id' => null,
                'price' => 15999,
                'discount' => 12,
                'brand_id' => $lenovo,
                'status' => 'active',
                'stock' => 50,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => '256GB',
                'image' => 'products/lenovo-ideatab-p12.jpg',
            ],

            // ========== Smart Watches ==========
            [
                'title' => 'Apple Watch Ultra 2 - Titanium - Orange Ocean Band',
                'slug' => 'apple-watch-ultra-2-titanium-orange-ocean-band',
                'summary' => 'أقوى ساعة Apple للمغامرين',
                'description' => '<p>شاشة 49mm، معالج S9 SiP، مقاومة الماء 100m، GPS دقيق، بطارية 36 ساعة.</p>',
                'cat_id' => $smartWatches,
                'child_cat_id' => null,
                'price' => 34999,
                'discount' => 0,
                'brand_id' => $apple,
                'status' => 'active',
                'stock' => 20,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => '49mm',
                'image' => 'products/apple-watch-ultra-2.jpg',
            ],
            [
                'title' => 'Apple Watch Series 9 - 45mm - Midnight Aluminum',
                'slug' => 'apple-watch-series-9-45mm-midnight-aluminum',
                'summary' => 'الجيل التاسع من Apple Watch',
                'description' => '<p>شاشة 45mm، معالج S9، Double Tap gesture، مقاومة الماء 50m.</p>',
                'cat_id' => $smartWatches,
                'child_cat_id' => null,
                'price' => 19999,
                'discount' => 5,
                'brand_id' => $apple,
                'status' => 'active',
                'stock' => 35,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => '45mm',
                'image' => 'products/apple-watch-series-9.jpg',
            ],
            [
                'title' => 'Samsung Galaxy Watch 6 Classic - 47mm - Black',
                'slug' => 'samsung-galaxy-watch-6-classic-47mm-black',
                'summary' => 'ساعة Samsung الكلاسيكية',
                'description' => '<p>شاشة 47mm Super AMOLED، حافة دوارة، Wear OS، مقاومة الماء 50m.</p>',
                'cat_id' => $smartWatches,
                'child_cat_id' => null,
                'price' => 12999,
                'discount' => 10,
                'brand_id' => $samsung,
                'status' => 'active',
                'stock' => 30,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => '47mm',
                'image' => 'products/samsung-galaxy-watch-6-classic.jpg',
            ],

            // ========== Headphones ==========
            [
                'title' => 'AirPods Pro 2nd Gen - USB-C',
                'slug' => 'airpods-pro-2nd-gen-usb-c',
                'summary' => 'أقوى AirPods مع إلغاء ضوضاء',
                'description' => '<p>إلغاء ضوضاء Adaptive، Spatial Audio، بطارية 6 ساعات، مقاومة العرق والماء IP54.</p>',
                'cat_id' => $headphones,
                'child_cat_id' => null,
                'price' => 9999,
                'discount' => 0,
                'brand_id' => $apple,
                'status' => 'active',
                'stock' => 60,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => 'One Size',
                'image' => 'products/airpods-pro-2.jpg',
            ],
            [
                'title' => 'AirPods Max - Space Gray',
                'slug' => 'airpods-max-space-gray',
                'summary' => 'سماعة over-ear فاخرة',
                'description' => '<p>إلغاء ضوضاء Active، Spatial Audio، Dynamic EQ، بطارية 20 ساعة.</p>',
                'cat_id' => $headphones,
                'child_cat_id' => null,
                'price' => 24999,
                'discount' => 5,
                'brand_id' => $apple,
                'status' => 'active',
                'stock' => 15,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => 'One Size',
                'image' => 'products/airpods-max.jpg',
            ],
            [
                'title' => 'Samsung Galaxy Buds 3 Pro - Silver',
                'slug' => 'samsung-galaxy-buds-3-pro-silver',
                'summary' => 'سماعة Samsung الرائدة',
                'description' => '<p>إلغاء ضوضاء Adaptive 2x أقوى، 360 Audio، بطارية 8 ساعات.</p>',
                'cat_id' => $headphones,
                'child_cat_id' => null,
                'price' => 6999,
                'discount' => 8,
                'brand_id' => $samsung,
                'status' => 'active',
                'stock' => 45,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => 'One Size',
                'image' => 'products/samsung-galaxy-buds-3-pro.jpg',
            ],

            // ========== Gaming ==========
            [
                'title' => 'Sony PlayStation 5 Slim - 1TB',
                'slug' => 'sony-playstation-5-slim-1tb',
                'summary' => 'PS5 الجديد أصغر وأخف',
                'description' => '<p>معالج AMD Zen 2، RDNA 2، 1TB SSD، دعم 4K 120Hz، Ray Tracing.</p>',
                'cat_id' => $gaming,
                'child_cat_id' => null,
                'price' => 24999,
                'discount' => 0,
                'brand_id' => $samsung, // أو Sony لو عندك
                'status' => 'active',
                'stock' => 20,
                'is_featured' => 1,
                'condition' => 'new',
                'size' => '1TB',
                'image' => 'products/ps5-slim.jpg',
            ],
        ];

        foreach ($products as $prod) {
            $product = Products::create([
                'title' => $prod['title'],
                'slug' => $prod['slug'],
                'summary' => $prod['summary'],
                'description' => $prod['description'],
                'cat_id' => $prod['cat_id'],
                'child_cat_id' => $prod['child_cat_id'],
                'price' => $prod['price'],
                'discount' => $prod['discount'],
                'brand_id' => $prod['brand_id'],
                'status' => $prod['status'],
                'stock' => $prod['stock'],
                'is_featured' => $prod['is_featured'],
                'condition' => $prod['condition'],
                'size' => $prod['size'],
            ]);

            // إضافة الصورة
            ProductImage::create([
                'product_id' => $product->id,
                'image' => $prod['image'],
            ]);

            // إضافة صورة ثانية (اختياري)
            ProductImage::create([
                'product_id' => $product->id,
                'image' => str_replace('.jpg', '-2.jpg', $prod['image']),
            ]);
        }


    }
}
